version: 2

updates:
  - package-ecosystem: npm
    directories:
      - '/'
      - '/apps/*'
      - '/packages/*'
    schedule:
      interval: daily
      timezone: 'Asia/Tokyo'
    open-pull-requests-limit: 10
    commit-message:
      prefix: '⬆️'
    target-branch: 'develop'
    groups:
      npm-dependencies:
        patterns:
          - '*'
        group-by: dependency-name
