packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  typescript: 5.9.2
  tsx: 4.20.6
  eslint: 9.39.1
  dotenv: 17.2.3
  dotenv-cli: 11.0.0
  prettier: 3.6.2

  hono: 4.10.3
  '@hono/node-server': 1.19.5
  fastify: 5.6.2
  '@fastify/cors': 11.1.0
  firebase: 12.6.0
  'firebase-admin': 13.6.0
  next: 16.0.7
  react: 19.2.1
  react-dom: 19.2.1

  '@types/node': 22.15.3
  '@types/react': 19.2.2
  '@types/react-dom': 19.2.2

  zod: 3.23.8
  '@hono/zod-validator': 0.4.1

  vitest: 2.1.8
  '@vitest/ui': 2.1.8
