packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  typescript: 5.9.2
  tsx: 4.20.6
  eslint: 9.39.1
  dotenv: 17.2.3
  prettier: 3.6.2

  fastify: 5.6.2
  next: 16.0.1
  react: 19.2.0
  react-dom: 19.2.0

  '@types/node': 22.15.3
  '@types/react': 19.2.2
  '@types/react-dom': 19.2.2
