packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  typescript: 5.9.2
  tsx: 4.20.6
  eslint: 9.39.1
  dotenv: 17.2.3
  dotenv-cli: 11.0.0
  prettier: 3.6.2

  expo: 54.0.27
  expo-constants: 18.0.11
  expo-font: 14.0.10
  expo-haptics: 15.0.8
  expo-image: 3.0.11
  expo-linking: 8.0.10
  expo-router: 6.0.17
  expo-splash-screen: 31.0.12
  expo-status-bar: 3.0.9
  expo-symbols: 1.0.8
  expo-system-ui: 6.0.9
  expo-web-browser: 15.0.10
  '@expo/metro-runtime': 6.1.2

  hono: 4.10.3
  '@hono/node-server': 1.19.5
  firebase: 12.6.0
  'firebase-admin': 13.6.0
  next: 16.0.7
  react: 19.2.1
  react-dom: 19.2.1
  react-native: 0.81.5

  '@types/node': 22.15.3
  '@types/react': 19.2.2
  '@types/react-dom': 19.2.2

  zod: 3.23.8
  '@hono/zod-validator': 0.4.1

  vitest: 2.1.8
  '@vitest/ui': 2.1.8
