/**
 * メーカーマスタのシードデータ
 */
export const manufacturers = [
  {
    name: 'ホンダ',
    nameEn: 'Honda',
    websiteUrl: 'https://www.honda.co.jp/motor/',
    country: '日本',
    isActive: true,
    bikes: [
      {
        modelName: 'Super Cub 50 Final Edition',
        displacement: 49,
        modelYear: 2025,
        modelCode: '2BH-AA09',
        releaseYear: 2024,
        releaseMonth: 12,
      },
      {
        modelName: 'Super Cub 50 HELLO KITTY',
        displacement: 49,
        modelYear: 2024,
        modelCode: '2BH-AA09',
        releaseYear: 2024,
        releaseMonth: 12,
      },
      {
        modelName: 'Super Cub 50',
        displacement: 49,
        modelYear: 2022,
        modelCode: '2BH-AA09',
        releaseYear: 2022,
        releaseMonth: 6,
      },
      {
        modelName: 'Super Cub 50 「天気の子」ver.',
        displacement: 49,
        modelYear: 2020,
        modelCode: '2BH-AA09',
        releaseYear: 2020,
        releaseMonth: 7,
      },
      {
        modelName: 'Super Cub 50 Street',
        displacement: 49,
        modelYear: 2019,
        modelCode: '2BH-AA09',
        releaseYear: 2019,
        releaseMonth: 3,
      },
      {
        modelName: 'Super Cub 50 60周年アニバーサリー',
        displacement: 49,
        modelYear: 2019,
        modelCode: '2BH-AA09',
        releaseYear: 2018,
        releaseMonth: 11,
      },
      {
        modelName: 'Super Cub 50',
        displacement: 49,
        modelYear: 2018,
        modelCode: '2BH-AA09',
        releaseYear: 2017,
        releaseMonth: 10,
      },
      {
        modelName: 'Super Cub 50 60周年アニバーサリー',
        displacement: 49,
        modelYear: 2019,
        modelCode: '2BH-AA09',
        releaseYear: 2018,
        releaseMonth: 11,
      },
      {
        modelName: 'Super Cub 50',
        displacement: 49,
        modelYear: 2018,
        modelCode: '2BH-AA09',
        releaseYear: 2017,
        releaseMonth: 10,
      },
      {
        modelName: 'Super Cub 50',
        displacement: 49,
        modelYear: 2012,
        modelCode: 'JBH-AA04',
        releaseYear: 2012,
        releaseMonth: 5,
      },
      {
        modelName: 'Super Cub 50',
        displacement: 49,
        modelYear: 2008,
        modelCode: 'JBH-AA01',
        releaseYear: 2008,
        releaseMonth: 8,
      },

      {
        modelName: 'CB400 SUPER FOUR HYPER VTEC Revo',
        displacement: 399,
        modelYear: 2020,
        modelCode: '2BL-NC42',
        releaseYear: 2020,
        releaseMonth: 1,
      },

      {
        modelName: 'CB250R',
        displacement: 249,
        modelYear: 2022,
        modelCode: '8BK-MC52',
        releaseYear: 2022,
        releaseMonth: 7,
      },
      {
        modelName: 'CB250R',
        displacement: 249,
        modelYear: 2019,
        modelCode: '2BK-MC52',
        releaseYear: 2019,
        releaseMonth: 4,
      },
      {
        modelName: 'CB250R ABS',
        displacement: 249,
        modelYear: 2018,
        modelCode: '2BK-MC52',
        releaseYear: 2018,
        releaseMonth: 5,
      },
      {
        modelName: 'CB250R',
        displacement: 249,
        modelYear: 2018,
        modelCode: '2BK-MC52',
        releaseYear: 2018,
        releaseMonth: 5,
      },
    ],
  },
  {
    name: 'ヤマハ',
    nameEn: 'Yamaha',
    websiteUrl: 'https://www.yamaha-motor.co.jp/mc/',
    country: '日本',
    isActive: true,
  },
  {
    name: 'スズキ',
    nameEn: 'Suzuki',
    websiteUrl: 'https://www1.suzuki.co.jp/motor/',
    country: '日本',
    isActive: true,
  },
  {
    name: 'カワサキ',
    nameEn: 'Kawasaki',
    websiteUrl: 'https://www.kawasaki-motors.com/mc/',
    country: '日本',
    isActive: true,
    bikes: [
      {
        modelName: 'Ninja 400',
        displacement: 398,
        modelYear: 2026,
        modelCode: '8BL-EX400L',
        releaseYear: 2025,
        releaseMonth: 11,
      },
      {
        modelName: 'Ninja 400',
        displacement: 398,
        modelYear: 2025,
        modelCode: '8BL-EX400L',
        releaseYear: 2025,
        releaseMonth: 4,
      },
    ],
  },
  {
    name: 'ドゥカティ',
    nameEn: 'Ducati',
    websiteUrl: 'https://www.ducati.com/',
    country: 'イタリア',
    isActive: true,
  },
  {
    name: 'BMW',
    nameEn: 'BMW Motorrad',
    websiteUrl: 'https://www.bmw-motorrad.jp/',
    country: 'ドイツ',
    isActive: true,
  },
  {
    name: 'ハーレーダビッドソン',
    nameEn: 'Harley-Davidson',
    websiteUrl: 'https://www.harley-davidson.com/',
    country: 'アメリカ',
    isActive: true,
  },
  {
    name: 'トライアンフ',
    nameEn: 'Triumph',
    websiteUrl: 'https://www.triumph-motorcycles.jp/',
    country: 'イギリス',
    isActive: true,
  },
  {
    name: 'KTM',
    nameEn: 'KTM',
    websiteUrl: 'https://www.ktm.com/',
    country: 'オーストリア',
    isActive: true,
  },
  {
    name: 'アプリリア',
    nameEn: 'Aprilia',
    websiteUrl: 'https://www.aprilia.com/',
    country: 'イタリア',
    isActive: true,
  },
]
