name: GCP Test

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  sample:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment:
      name: production

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/540084344486/locations/global/workloadIdentityPools/github/providers/github '
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
